config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :departments, except: [:index, :show]
    resources :users, except: [:show]
  end

  concern :stats do
    get 'stats', on: :member
  end

  resources :departments, only: [:index, :show], concerns: :stats
  resources :users, only: [:show], concerns: :stats
  resources :worktimes, only: [:index, :show, :create, :edit, :update, :destroy], path: 'worktime'
  resources :records do
    get :vacation, :sickness, :day_off, on: :new
    get :pending,     on: :collection
    get :requested,   on: :collection
    get :bookkeeping, on: :collection
    get :boss_approve,    on: :member
    get :boss_disapprove, on: :member
    get :bookkeeper_approve, on: :member
    resources :comments, except: [:index, :show], shallow: true
  end

  root 'root#index'
end

app/models/department.rb
class Department < ActiveRecord::Base
  include Hierarchy

  belongs_to :parent,  class_name: 'Department', foreign_key: 'parent_id'
  belongs_to :boss,    class_name: 'User',       foreign_key: 'boss_id'

  has_many :employees, class_name: 'User',       foreign_key: 'department_id'
  has_many :children,  class_name: 'Department', foreign_key: 'parent_id'

  validates :title, presence: true
  validates_with ReachRootValidator

  scope :top_level, -> { where parent_id: nil }
end

app/models/department/hierarchy.rb
class Department < ActiveRecord::Base
  module Hierarchy
    extend ActiveSupport::Concern

    included do
      def hierarchy
        hierarchy = []
        current   = self
        hierarchy << current
        while current = current.parent
          hierarchy << current
        end
        hierarchy.reverse!
      end

      def hierarchy_title
        "#{'―' * (hierarchy.count - 1)} #{title}"
      end
    end

    class_methods do
      def hierarchy_tree
        result = []
        top_level.order(:id).each do |d|
          add_children_of_parent d, result
        end
        result
      end

      def add_children_of_parent(parent, result)
        result << parent
        return if parent.children.blank?
        parent.children.each do |child|
          add_children_of_parent(child, result)
        end
      end
    end
  end
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::AdminController
  before_action :set_department, only: [:edit, :update, :destroy]

  def new
    parent_id = Rails.application.routes.recognize_path(request.referrer)[:id]
    @department = Department.new parent_id: parent_id
  end

  def create
    @department = Department.new department_params
    if @department.save
      redirect_to department_path @department
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @department.update department_params
    if @department.save
      redirect_to department_path @department
    else
      render 'edit'
    end
  end

  def destroy
    redirect_path = (@department.parent.present? ? @department.parent : departments_path)
    Service::DeleteDepartment.new(@department).delete
    redirect_to redirect_path
  end

private

  def set_department
    @department = Department.find params[:id]
  end

  def department_params
    params.require(:department).permit(:title, :parent_id, :boss_id)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department,  only: :show
  before_action :set_breadcrumbs, only: [:index, :show]

  def index
    @departments = Department.top_level
    @users = User.without_department.decorate
    render :show
  end

  def show
    @departments = @department.children
    @users = @department.employees.decorate
  end

  def stats
  end

private

  def set_department
    @department = Department.find params[:id]
  end

  def set_breadcrumbs
    add_breadcrumb 'Root', departments_path
    if @department
      @department.hierarchy.each do |dep|
        add_breadcrumb dep.title, department_path(dep)
      end
    end
  end
end

app/views/departments/_department.html.haml
.panel.panel-custom
  %a.panel-heading{href: department_path(department)}
    %h3.panel-title= department.title
  .panel-body
    Contains
    = pluralize department.children.count, t('terms.department')
    and
    = pluralize department.employees.count, t('terms.employee')

app/views/departments/_list.html.haml
.row
  .col-sm-6
    %h3.block-title= t 'terms.departments'
    = contains = render @departments
    - unless contains
      .alert= t 'messages.not_contains_departments'

  .col-sm-6
    %h3.block-title= t 'terms.employees'
    .list-group
      = contains = render @users
      - unless contains
        .alert= t 'messages.not_contains_users'

app/views/departments/show.html.haml
.departments-page

  %ul.breadcrumb= render_breadcrumbs

  .actions
    - if current_user.has_role? :admin
      = link_to t('actions.add_department'), new_admin_department_path, class: 'btn btn-sm btn-primary'
      = link_to t('actions.add_employee'), new_admin_user_path, class: 'btn btn-sm btn-primary'
      - if @department
        = link_to t('actions.edit_department'), edit_admin_department_path(@department), class: 'btn btn-sm btn-info'
        = link_to t('actions.destroy_department'), [:admin, @department], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

  = render 'list'

app/views/departments/stats.html.haml
%h1 Department
%h2 Stats