config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :departments, except: [:index, :show]
    resources :users, except: [:show]
  end

  concern :stats do
    get 'stats', on: :member
  end

  resources :departments, only: [:index, :show], concerns: :stats
  resources :users, only: [:show], concerns: :stats
  resources :worktimes, only: [:index, :show, :create, :edit, :update, :destroy], path: 'worktime'
  resources :records do
    get :vacation, :sickness, :day_off, on: :new
    get :pending,     on: :collection
    get :requested,   on: :collection
    get :bookkeeping, on: :collection
    get :boss_approve,    on: :member
    get :boss_disapprove, on: :member
    get :bookkeeper_approve, on: :member
    resources :comments, except: [:index, :show], shallow: true
  end

  root 'root#index'
end

app/models/record.rb
require 'valid_email/email_validator'

class Record < ActiveRecord::Base
  attr_accessor :comment

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :date_from, :date_to, date: true, unless: :is_record_worktime?
  validate :dates_cannot_be_in_the_past,
           :date_from_lesser_than_date_to,
           :emails_should_be_valid,
           :records_should_not_overlap,
           unless: :is_record_worktime?

  after_save :send_notifications

private

  def is_record_worktime?
    self.is_a? Worktime
  end

  def send_notifications
    puts "Let's send some notifications for those emails: #{emails}"
  end

  def dates_cannot_be_in_the_past
    if date_from && date_from < Date.today
      errors.add :date_from, 'can\'t be in the past'
    end
    if date_to && date_to < Date.today
      errors.add :date_to, 'can\'t be in the past'
    end
  end

  def date_from_lesser_than_date_to
    if date_from && date_to && date_from > date_to
      errors.add :date_to, 'can\'t be before date_from'
    end
  end

  def emails_should_be_valid
    emails_array = emails.split
    emails_array.each_with_index do |email, index|
      errors.add(:emails, "#{email} is invalid") unless ValidateEmail.valid? email
    end
  end

  def records_should_not_overlap
    r1, r2, r3 = OverlappingRecords.result user, date_from, date_to, self
    errors.add :date_from, 'overlaps other record' if r1.present? or r3.present?
    errors.add :date_to, 'overlaps other record'   if r2.present? or r3.present?
  end
end

app/models/records/day_off.rb
class DayOff < Record
end

app/models/records/sickness.rb
class Sickness < Record
end

app/models/records/vacation.rb
class Vacation < Record
end

app/models/records/vatation.rb
class Vacation < Record

end

app/models/records/worktime.rb
class Worktime < Record
  attr_accessor :time_from, :time_to, :day

  has_one :comment, foreign_key: 'record_id', dependent: :destroy

  scope :user, -> (user) { where user: user }

  def self.for_day(day)
    from = DateTime.parse day
    where 'date_from >= ? and date_to <= ?', from, from + 1.day
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  authorize_resource
  before_action :set_record, only: [:show, :edit, :update, :destroy, :boss_approve, :boss_disapprove, :bookkeeper_approve]

  def create
    @record = Workflow::Record.new(current_user, Record.new, record_params).process
    handle_update_or_create
  end

  def update
    @record = Workflow::Record.new(current_user, @record, record_params).process
    handle_update_or_create
  end

  def destroy
    @record.destroy
    redirect_to :back
  end

  def vacation
    @record = Vacation.new
    render 'new'
  end

  def sickness
    @record = Sickness.new
    render 'new'
  end

  def day_off
    @record = DayOff.new
    render 'new'
  end

  def pending
    @records = PendingRecordsForBoss.result current_user
  end

  def requested
    # todo: should display only relevant records (this month?)
    # todo: remove this select from controller
    @records = current_user.records.where.not(type: 'Worktime')
  end

  def bookkeeping
    # todo: should display only relevant records (last month)
    # todo: remove this select from controller
    @records = Record.all.where(bookkeeper_approved: nil, type: %w([Vacation Sickness]))
  end

  def boss_approve
    @record.update_attribute :boss_approved, true
    redirect_to :back
  end

  def boss_disapprove
    @record.update_attribute :boss_approved, false
    redirect_to :back
  end

  def bookkeeper_approve
    @record.update_attribute :bookkeeper_approved, true
    redirect_to :back
  end

private

  def handle_update_or_create
    if @record.errors.empty?
      redirect_to requested_records_path
    else
      render 'new'
    end
  end

  def record_params
    [:record, :vacation, :day_off, :sickness].each do |type|
      return params.require(type).permit(:type, :date_from, :date_to, :emails, :comment) if params.has_key? type
    end
  end

  def set_record
    @record = Record.find params[:id]
  end
end

app/helpers/record_helper.rb
module RecordHelper
  def record_status(record)
    case record.boss_approved
      when true
        return 'Approved'
      when false
        return 'Disapproved'
      when nil
        return 'Pending'
    end
  end
end

app/views/records/_form.html.haml
- if defined? title
  .row
    .col-sm-6
      %h2.col-sm-offset-3.form-action-title= title

= simple_form_for @record, url: (@record.new_record? ? records_path : record_path(@record)), html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f|
  = f.input :type, as: 'hidden'
  .row= f.input :date_from, as: :date_picker, wrapper_html: { class: 'col-sm-6' }
  .row= f.input :date_to,   as: :date_picker, wrapper_html: { class: 'col-sm-6' }
  .row= f.input :emails, placeholder: 'List of emails separated by space', as: :string, wrapper_html: { class: 'col-sm-6' }
  .row= f.input :comment, placeholder: 'I don\'t want to live on this planet anymore', as: :text, wrapper_html: { class: 'col-sm-6' }
  .row
    .col-sm-6
      .col-sm-offset-3= f.submit class: 'btn btn-primary'

app/views/records/_requested_record.html.haml
- record = requested_record
.col-sm-6
  .panel.panel-default
    .panel-heading
      .panel-title
        .row
          .col-sm-6
            = record.type
            %span.text-muted= record.user.email if current_page? action: 'pending'
          .col-sm-6.text-right
            = link_to fa_icon('pencil'), edit_record_path(record)
            = link_to fa_icon('remove'), record_path(record), method: :delete
    .panel-body
      .well-sm
        %strong From:
        = time_tag record.date_from.to_date
        |
        %strong To:
        = time_tag record.date_to.to_date
        |
        %strong Status:
        = record_status(record)
      - if record.comments.any?
        = render partial: 'comments/comment_for_record', collection: record.comments
      .well-sm
        = link_to 'Add comment', new_record_comment_path(record), class: 'btn btn-primary'
        - if current_page? action: 'pending'
          = link_to 'Approve', boss_approve_record_path(record), class: 'btn btn-success'
          = link_to 'Disapprove', boss_disapprove_record_path(record), class: 'btn btn-danger'

app/views/records/bookkeeping.html.haml
%h1 Records
%h2 Bookkeeping

%table.table.table-responsive
  %thead
    %th ID
    %th Type
    %th From
    %th To
  %tbody
    - @records.each do |r|
      %tr
        %td= r.id
        %td= r.type
        %td= r.date_from.to_date
        %td= r.date_to.to_date
        %td= link_to 'Approve', bookkeeper_approve_record_path(r)

app/views/records/edit.html.haml
= render 'form', title: ("#{t('actions.edit').capitalize} #{t('terms.' + @record.type.downcase)}").humanize

app/views/records/index.html.haml
%h1 Records
%h2 Index

app/views/records/new.html.haml
= render 'form', title: ("#{t('actions.new').capitalize} #{t('terms.' + @record.type.downcase)}").humanize

app/views/records/pending.html.haml
%h1 Record
%h2 Pending

- if @records.present?
  .row
    = render partial: 'records/requested_record', collection: @records

app/views/records/requested.html.haml
%h1 Record
%h2 Requested

- if @records.present?
  .row
    = render partial: 'records/requested_record', collection: @records

app/views/records/show.html.haml
%h1= "Record ##{@record.id}"
%h2 Comments
%table.table.table-responsive
  %thead
    %th User
    %th Message
  %tbody
    - @record.comments.each do |c|
      %tr
        %td= c.user.email
        %td= c.message