config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :departments, except: [:index, :show]
    resources :users, except: [:show]
  end

  concern :stats do
    get 'stats', on: :member
  end

  resources :departments, only: [:index, :show], concerns: :stats
  resources :users, only: [:show], concerns: :stats
  resources :worktimes, only: [:index, :show, :create, :edit, :update, :destroy], path: 'worktime'
  resources :records do
    get :vacation, :sickness, :day_off, on: :new
    get :pending,     on: :collection
    get :requested,   on: :collection
    get :bookkeeping, on: :collection
    get :boss_approve,    on: :member
    get :boss_disapprove, on: :member
    get :bookkeeper_approve, on: :member
    resources :comments, except: [:index, :show], shallow: true
  end

  root 'root#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Wisper::Publisher
  include RoleModel

  roles_attribute :roles_mask
  roles :bookkeeper, :admin

  belongs_to :department
  has_one :boss_of, class_name: 'Department', foreign_key: 'boss_id'

  has_many :records
  has_many :comments

  validates :email, :first_name, :last_name, presence: true

  scope :without_department, -> { where department: nil }
  scope :ordered, -> { order :id }

  after_create do
    broadcast :after_create_user, self
  end

  def self.by_department(department)
    where department: department
  end

  devise :database_authenticatable, :rememberable, :trackable, :validatable, :recoverable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.ordered
  end

  def create
    @user = User.new user_params
    @user.password = Devise.friendly_token[0, 8]
    @user.subscribe Notification::NewEmployee.new
    if @user.save
      redirect_to @user.department.present? ? department_path(@user.department) : departments_path
    else
      render 'new'
    end
  end

  def new
    department_id = Rails.application.routes.recognize_path(request.referrer)[:id]
    @user = User.new department_id: department_id
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    redirect_path = (@user.department.present? ? @user.department : departments_path) # todo: remove it from controller, to helper, maybe
    Service::DeleteUser.new(@user).delete
    redirect_to redirect_path
  end

  private

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :department_id, :first_name, :middle_name, :last_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end

  def stats
  end

  private

  def set_user
    @user = User.find params[:id]
  end
end

app/views/admin/users/_form.html.haml
- if defined? title
  .row
    .col-sm-6
      %h2.col-sm-offset-3.form-action-title= title

= simple_form_for @user, html: { class: 'form-horizontal' }, wrapper: :horizontal_form, url: [:admin, @user] do |f|
  .row= f.input :first_name, placeholder: 'George', wrapper_html: { class: 'col-sm-6' }
  .row= f.input :middle_name, placeholder: 'Walton', wrapper_html: { class: 'col-sm-6' }
  .row= f.input :last_name, placeholder: 'Lucas', wrapper_html: { class: 'col-sm-6' }
  .row= f.input :email, placeholder: 'father@lucasarts.com', wrapper_html: { class: 'col-sm-6' }
  .row= f.input :department_id, collection: Department.hierarchy_tree, label_method: :hierarchy_title, include_blank: 'Root', wrapper_html: { class: 'col-sm-6' }
  .row
    .col-sm-6
      .col-sm-offset-3= f.submit class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
= render 'form', title: "#{t('actions.edit').capitalize} #{t('terms.employee')}"

app/views/admin/users/index.html.haml
%h1
  All users
  %span.small= link_to 'New user', new_admin_user_path

%table.table.table-responsive
  %thead
    %th ID
    %th Name
    %th Email
    %th Department
    %th Boss of
    %th
  %tbody
    - @users.each do |u|
      %tr
        %td= link_to u.id, edit_admin_user_path(u)
        %td= "#{u.first_name} #{u.middle_name} #{u.last_name}"
        %td= u.email
        %td= u.department.title unless u.department.nil?
        %td= u.boss_of.title unless u.boss_of.nil?
        %td= link_to 'Remove', admin_user_path(u), method: :delete

app/views/admin/users/new.html.haml
= render 'form', title: "#{t('actions.new').capitalize} #{t('terms.employee')}"