config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :departments, except: [:index, :show]
    resources :users, except: [:show]
  end

  concern :stats do
    get 'stats', on: :member
  end

  resources :departments, only: [:index, :show], concerns: :stats
  resources :users, only: [:show], concerns: :stats
  resources :worktimes, only: [:index, :show, :create, :edit, :update, :destroy], path: 'worktime'
  resources :records do
    get :vacation, :sickness, :day_off, on: :new
    get :pending,     on: :collection
    get :requested,   on: :collection
    get :bookkeeping, on: :collection
    get :boss_approve,    on: :member
    get :boss_disapprove, on: :member
    get :bookkeeper_approve, on: :member
    resources :comments, except: [:index, :show], shallow: true
  end

  root 'root#index'
end

app/views/layouts/_flash.html.haml
- if flash[:alert]
  .alert.alert-danger.alert-dismissible
    %button.close{'data-dismiss' => 'alert', 'aria-label' => 'Close'}
      %span{'aria-hidden' => true} &times;
    = flash[:alert]

app/views/layouts/_menu.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: '/'}= t 'title'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to t('pages.calendar'), worktimes_path
        %li
          = link_to t('pages.departments'), departments_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            = t 'actions.add_request'
            %span.caret
          %ul.dropdown-menu{role: 'menu'}
            %li
              = link_to t('terms.sickness'), sickness_new_record_path
            %li
              = link_to t('terms.vacation'), vacation_new_record_path
            %li
              = link_to t('terms.day_off'), day_off_new_record_path

      %ul.nav.navbar-nav.navbar-right

        - if can? :pending, Record
          %li= link_to 'Pending records', pending_records_path

        - if can? :bookkeeping, Record
          %li= link_to t('actions.bookkeeping'), bookkeeping_records_path

        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            = current_user.email
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              = link_to t('pages.requested'), requested_records_path
            %li
              = link_to t('actions.sign_out'), destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? "#{yield(:title)} - #{t 'title'}": "#{t 'title'}"
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/menu'
      = render 'layouts/flash'
      = yield
    = javascript_include_tag 'application'

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? "#{yield(:title)} - #{t 'title'}": "#{t 'title'}"
    = stylesheet_link_tag 'devise', media: 'all'
    = csrf_meta_tags
  %body
    - if Rails.env.development?
      = switch_user_select
    = yield